### ISSUE TITLE
no helper_functions

### ISSUE THREAD

**Issue by ever4cyth** [Super-Hippo/CUDAMPF#3]
In file included from main_function.cpp:7:0:
header_def.h:20:30: fatal error: helper_functions.h: No such file or directory
 #include <helper_functions.h>
                              ^
compilation terminated.
make: **\* [main_function.o] Error 1

**Comment by Super-Hippo** [comment]
You could find this header file "helper_functions.h" under this directory:
$(CUDA_PATH)//samples/common/inc.
Usually, your default $(CUDA_PATH) is like "/usr/local/cuda-x.x/"
Thus, please update cuda version and check out whether you have above directory in your system.

**Comment by ever4cyth** [comment]
Thanks, I realized the path to cuda is not correct since I used cuda-7.5. Now another error

./CUDAMPF -msv ../100.hmm ../Pfam-A.fasta 
Your input is: -msv
.fsa file open well
Got hmm length
In this database, we have 10371396 seqs.
The HMM size is 100.
msv:2
vit 2
.hmm file open well
MSV MU: -9.567800, LAMBDA: 0.717550
viterbi MU: -10.300500, LAMBDA: 0.717550
Forward MU: -3.482100, LAMBDA: 0.717550
.hmm file open well
.hmm file open well_trans
model process time: 1.557000 (ms)
.fsa file open well

 Total residue = 1632625946
.fsa file open well
the seq database has been aligned!!
whole seq database process time: 73320.335938 (ms)
WARP_SIZE = 32
SMX = 5
MAX_SMEM = 65536
========== MSV Filter ==========
SMEM MSV::warps per block: 32
SMEM MSV::resident blocks per SMX: 2
read .cuh file time: 0.072000 (ms)
Using SMEM: load in "SMEM_MSV.cuh" kernel file...
Available registers per thread is: 32
Alloc & H to D Copy time: 1545.005981 (ms)
nvrtc Creat and Compile: 437.265015 (ms)
Compile & Load time: 129.595993 (ms)
checkCudaErrors() Driver API error = 0702 "CUDA_ERROR_LAUNCH_TIMEOUT" from file <RTC_MSV.cpp>, line 181.

**Comment by Super-Hippo** [comment]
.... are you testing on your local machine with terminal? 
This case may happen when kernel time is longer than a threshold point of system stalling. If so, try it remotely will solve this.
You could first test a smaller dataset to see whether kernel works.
